include $(THEOS)/makefiles/common.mk

BUNDLE_NAME = VPNTriggerManagerPrefs
VPNTriggerManagerPrefs_FILES = VTMRootListController.m
VPNTriggerManagerPrefs_FRAMEWORKS = UIKit
VPNTriggerManagerPrefs_PRIVATE_FRAMEWORKS = Preferences
VPNTriggerManagerPrefs_INSTALL_PATH = /Library/PreferenceBundles
VPNTriggerManagerPrefs_CFLAGS = -fobjc-arc

include $(THEOS_MAKE_PATH)/bundle.mk

